# syntax=docker/dockerfile:1.6
# =============================================================================
# Multi-stage Dockerfile — NUMU V3 BYOT storefront (numu-storefront)
# =============================================================================
# Uses Next.js *standalone* output (next.config.ts `output: "standalone"`) so
# the runner image carries only the self-contained server + a minimal
# node_modules, not the full dependency tree.
#
# Two things standalone does NOT bundle, copied explicitly in the runner:
#   - .next/static  (client chunks)
#   - public/       (incl. the BYOT federation runtime in public/__numu-runtime/,
#                    generated by the prebuild step scripts/build-runtime.mjs)
# =============================================================================

# ---------- deps ----------
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

# ---------- builder ----------
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

# Build-time PUBLIC env. NEXT_PUBLIC_* values are inlined into the client
# bundle at build time — runtime container env has no effect on them, so
# anything the browser needs must be passed here via --build-arg.
ARG NEXT_PUBLIC_NUMU_ENV=production
ARG NEXT_PUBLIC_BYOT_BUNDLE_HOSTS
ARG NEXT_PUBLIC_GOOGLE_MAPS_KEY
ENV NEXT_PUBLIC_NUMU_ENV=$NEXT_PUBLIC_NUMU_ENV
ENV NEXT_PUBLIC_BYOT_BUNDLE_HOSTS=$NEXT_PUBLIC_BYOT_BUNDLE_HOSTS
# The CD passes --build-arg NEXT_PUBLIC_GOOGLE_MAPS_KEY; without this ARG/ENV
# pair it never reaches `next build`, so canUseMaps() stayed false and the
# checkout map-pin never rendered.
ENV NEXT_PUBLIC_GOOGLE_MAPS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_KEY

# `npm run build` runs the prebuild hook (scripts/build-runtime.mjs) which
# bundles the BYOT federation runtime into public/__numu-runtime/, then
# `next build` emits .next/standalone + .next/static.
RUN npm run build

# ---------- runner ----------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Standalone server.js honours PORT + HOSTNAME. nginx reaches us by
# container name on the shared docker network, so we only bind internally.
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Self-contained server + its minimal node_modules (standalone output).
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Client static chunks (not part of standalone).
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# public/ incl. the generated BYOT federation runtime (__numu-runtime/).
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# Healthcheck hits a tenant-independent static asset. `/` 404s here — every
# page lives under /[domain] — so we probe the always-present BYOT runtime
# manifest instead.
# Probe 127.0.0.1 (not localhost) — the container's /etc/hosts maps localhost
# to ::1 too, and busybox wget tries IPv6 first while the server binds IPv4.
HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 \
    CMD wget --quiet --spider http://127.0.0.1:3000/__numu-runtime/manifest.json || exit 1

CMD ["node", "server.js"]
