import path from "node:path";
import type { NextConfig } from "next";

const isProd = process.env.NEXT_PUBLIC_NUMU_ENV === "production";

const nextConfig: NextConfig = {
  // Produce a self-contained server bundle (`.next/standalone/server.js`
  // + a minimal node_modules) so the Docker runner image stays lean —
  // no full node_modules copy. NOTE: `public/` and `.next/static` are
  // NOT included in standalone output and must be copied into the image
  // alongside it (the Dockerfile does this). The BYOT federation runtime
  // in `public/__numu-runtime/` is generated by the prebuild step and
  // ships via that `public/` copy.
  output: "standalone",

  // Pin the workspace root so Turbopack doesn't walk up to the parent
  // directory looking for package.json/lockfiles.
  turbopack: {
    root: path.resolve(__dirname),
  },

  // Allow the merchant hub's V3 customizer iframe (default :8080), the theme
  // dist server (:5173) and plain `127.0.0.1` browsing to reach Next dev
  // resources. Production builds don't need this — it's a dev-only escape
  // hatch.
  //
  // ⚠️ These MUST be bare hostnames. Next matches them against the request's
  // hostname only (`isCsrfOriginAllowed` → `matchWildcardDomain`), so a
  // port-qualified entry like "127.0.0.1:8080" can never match anything and is
  // silently inert. The list used to be entirely port-qualified, which meant
  // it did nothing at all.
  //
  // This is not cosmetic. Next only hardcodes `localhost` and `*.localhost`,
  // so browsing `http://127.0.0.1:3100` was blocked — and a blocked
  // `/_next/webpack-hmr` upgrade is FATAL in Next 16, not merely "no HMR":
  // `experimental.reactDebugChannel` defaults to true, the RSC Flight client's
  // debug channel is fed exclusively by that socket, and `hydrate()` awaits it.
  // Kill the socket and hydration parks forever with no error — React loads,
  // the skeleton renders, no effect ever runs, so no theme bundle and no
  // interactivity. Measured: `localhost:3100` → 498 React fibers and the theme
  // mounted; `127.0.0.1:3100` → 1 fiber and a permanent skeleton.
  // (Escape hatch if a socket ever dies for another reason — a proxy, a port
  // clash: set `experimental.reactDebugChannel: false`, which decouples
  // hydration from HMR so the failure degrades to "no hot reload".)
  ...(isProd
    ? {}
    : {
        allowedDevOrigins: [
          "127.0.0.1",
          "localhost",
          "*.localhost",
        ],
      }),

  // Cap how aggressively the dev image cache fills the disk. Default
  // minimumCacheTTL is 60s; raise to 1 hour so we re-fetch less often,
  // but the cap matters more — see deviceSizes/imageSizes below.
  images: {
    minimumCacheTTL: 60 * 60,
    // Restrict the device + image breakpoints so /_next/image doesn't
    // generate 8+ variants per source. Each variant lives in .next/cache.
    deviceSizes: [640, 768, 1024, 1280, 1920],
    imageSizes: [64, 128, 256, 384],
    remotePatterns: [
      { protocol: "https", hostname: "**.numu.io" },
      { protocol: "https", hostname: "**.numueg.app" },
      { protocol: "https", hostname: "**.r2.cloudflarestorage.com" },
      // In dev, allow any HTTPS host so a merchant can drop in any URL
      // for hero images; in prod we narrow to known CDNs.
      ...(isProd ? [] : [{ protocol: "https" as const, hostname: "**" }]),
    ],
  },

  // Skip generating source maps in dev — they're a large chunk of the
  // .next/cache footprint on Windows. Re-enable selectively if you're
  // debugging a hard-to-read stack trace.
  productionBrowserSourceMaps: false,

  experimental: {
    // Enable PPR (partial prerendering) once stable on Next 16.
    // ppr: true,
  },

  // Allow the merchant hub's theme editor to iframe the storefront for live
  // preview. Cloudflare's "Add security headers" managed transform stamps
  // `X-Frame-Options: SAMEORIGIN` on every numueg.app response, which would
  // otherwise block the cross-subdomain embed. Setting a CSP `frame-ancestors`
  // directive overrides X-Frame-Options per CSP Level 2 spec (browsers ignore
  // XFO when frame-ancestors is present in an enforced policy).
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "Content-Security-Policy",
            value:
              "frame-ancestors 'self' https://numueg.app https://*.numueg.app http://localhost:* http://127.0.0.1:*",
          },
        ],
      },
      {
        // The runtime manifest is the ONE file here that must never be cached
        // hard. It is an unversioned, mutable pointer naming the SDK version
        // the host currently serves, and `external-loader` gates every theme
        // bundle on it: if a browser holds a stale copy, a correctly deployed
        // host still renders "Theme built against SDK 0.12 but host runtime
        // serves 0.10.0" and the storefront is blank. It shipped under the
        // blanket rule below AND picked up an `immutable, max-age=31536000`
        // header appended upstream (nginx), which pinned it for a year.
        //
        // Listed BEFORE the wildcard so this more specific source wins. The
        // client also fetches it with `cache: "no-cache"`, because an upstream
        // header we do not control here can still contradict this.
        source: "/__numu-runtime/manifest.json",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=0, must-revalidate",
          },
        ],
      },
      {
        // BYOT federation runtime (react/react-dom/sdk/chunks, ~300KB).
        // Next serves public/ with `max-age=0`, so every navigation (themes
        // do full-page <a> loads) re-fetched/re-validated the whole runtime —
        // the dominant nav latency (SSR itself is ~150ms). These files are
        // compatible within an SDK major, so cache them a few minutes +
        // revalidate in the background; a deploy still propagates within
        // minutes. theme.js (R2) is already cached the same way.
        source: "/__numu-runtime/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=300, stale-while-revalidate=86400",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
